---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tailscale-router-auth
  namespace: kube-system
spec:
  encryptedData:
    TS_AUTHKEY: AgBy8oZulWRk8IJlqWEXiItkKTz0wcVrw09puwQbS0edwvd1ORiIW6L0SFnTw/5ei1Eu+2NStB4IkVKYuAQtggAI9GqGvkjisN6aum5YHGxjaFexiVUnVdjEXB6TD3RvwOxQfzkT+CANH1nebZWE86QCpFqfXej6fSvXEzwqzB84TuwLLEBV143GdYTMgUdobegZyGaK96rOyW8WdP8n7IkgdMuPeXpDk6lJW8UGWzf0G3jqzX7GdLTYqrG+QX/BprniZiDRjgDUdvoQEalC55CAcJIJRKMVCw/kS2+6dXtbFTNQpr3O4jiofDIdTkwMTnQ3wTlePR9CtriRFxge3hNma89B7k9WbDZvCRJ88Bc7nja4yGfnruLBilrmbtSQfSho9fi0hiY8ROlbPhAx3BQY6Yudgrf5SrNbxGsk2e5SCt1QJfwAstgTm2Jvv979yCOP4xd4Qztj6VBZ3Ouqswrk9xv2JE0lGGvebEnOGQau0L6i6MozRG18Jkvl7HcxYlrq/L9M4p+A2UnB7wJbsQbguGgBc+34B1zoMxJdbYuOtFalvxUJf2T0UJtYjE09Wq0Qr0xIysv/DHV7Dync/vZXo7yoHIcbO7EJqaA46RsSOKbxBiXu/MnMdDNrAh0vB/04/KjuEv9YorB8WY9N3MO8W08FlRNj1tEhGZTgyERp8Vk74N6ECgvoEEYfBHTTW4g9IdozWfwGRbUQhz96IgXgCjFO/DYuUx6xTXeu9IfiNfqchsWUFdUA+T/xa4pEspYeAdvQeBuvswAz9XBkFWS2R/DcVPOnw4L2oZ0ROcUyFuRaRt+AzT9I
  template:
    metadata:
      name: tailscale-router-auth
      namespace: kube-system
