apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 00-namespaces
  - 10-metallb
  - 30-k8s-gateway
  - 40-ingress-nginx
  - 45-sealed-secrets
  - 50-cnpg
  - 60-system-upgrade
  - 70-monitoring
  - 75-promtail
  - 80-tailscale-router
